{
  imports = [
    ./immich.nix
    ./sabnzbd.nix
    ./prowlarr.nix
    ./sonarr.nix
    ./radarr.nix
    ./seafile.nix
    ./tdarr.nix
    ./jellyfin.nix
    ./terraria.nix
    ./lidarr.nix
    ./jellyseerr.nix
    ./bazarr.nix
    ./homepage.nix
    ./wger.nix
    ./sops.nix
  ];
}
